name: CI

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ruby:2.7
        steps:
            - uses: actions/checkout@v2
            - name: Build jekyll site
              run: |
                  bundle install 
                  bundle exec jekyll build
